/**
 * RoleWithAI Mock Data Service
 * Provides realistic 2026 market data for development and testing
 */

import { MarketVitals, JobMatch, LedgerEntry, GhostSignal } from '@/lib/types'
import { calculateTruthScore, ghostSignalToInput } from '@/lib/truthScoreEngine'
import { generateJobDialogue, generateLedgerNote } from '@/lib/narrativeEngine'

/**
 * Get current market vitals (2026 realistic data)
 */
export function getMarketVitals(): MarketVitals {
  return {
    hiringVelocity: 4, // +4% hiring increase
    ghostingRate: 12, // +12% ghosting increase
    impactPoints: 127, // User's accumulated points
    dailyBrief: '', // Will be generated by Morning Brief agent
  }
}

/**
 * Get mock job matches with intelligence analysis
 */
export function getMockJobMatches(): JobMatch[] {
  const baseJobs = [
    {
      id: '1',
      title: 'Senior Product Designer',
      company: 'TechCorp Inc.',
      location: 'San Francisco, CA',
      postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
      signalBreakdown: {
        recruiterActivity: 'High' as const,
        repostFrequency: 'Low' as const,
        communitySentiment: 'Positive' as const,
      },
    },
    {
      id: '2',
      title: 'UX Lead',
      company: 'DesignStudio',
      location: 'Remote',
      postedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
      signalBreakdown: {
        recruiterActivity: 'Moderate' as const,
        repostFrequency: 'None' as const,
        communitySentiment: 'Neutral' as const,
      },
    },
    {
      id: '3',
      title: 'Product Manager',
      company: 'StartupXYZ',
      location: 'New York, NY',
      postedDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(), // 45 days ago
      signalBreakdown: {
        recruiterActivity: 'None' as const,
        repostFrequency: 'High' as const,
        communitySentiment: 'Negative' as const,
      },
    },
    {
      id: '4',
      title: 'Frontend Engineer',
      company: 'ScaleUp Co.',
      location: 'Austin, TX',
      postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
      signalBreakdown: {
        recruiterActivity: 'High' as const,
        repostFrequency: 'None' as const,
        communitySentiment: 'Positive' as const,
      },
    },
    {
      id: '5',
      title: 'Full Stack Developer',
      company: 'Evergreen Corp',
      location: 'Seattle, WA',
      postedDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(), // 60 days ago
      signalBreakdown: {
        recruiterActivity: 'None' as const,
        repostFrequency: 'High' as const,
        communitySentiment: 'Negative' as const,
      },
    },
  ]
  
  // Calculate truth scores and generate dialogue
  const timeOfDay = getTimeOfDay()
  return baseJobs.map((job) => {
    const truthScoreResult = calculateTruthScore(
      ghostSignalToInput(job.signalBreakdown, job.postedDate)
    )
    
    const jobMatch: JobMatch = {
      id: job.id,
      title: job.title,
      company: job.company,
      location: job.location,
      postedDate: job.postedDate,
      truthScore: truthScoreResult.truthScore,
      ghostRisk: truthScoreResult.ghostRisk,
      echoDialogue: generateJobDialogue(
        {
          ...job,
          truthScore: truthScoreResult.truthScore,
          ghostRisk: truthScoreResult.ghostRisk,
          echoDialogue: '',
          whyScore: '',
        },
        timeOfDay
      ),
      signalBreakdown: job.signalBreakdown,
      whyScore: truthScoreResult.whyScore,
    }
    
    return jobMatch
  })
}

/**
 * Get mock ledger entries
 */
export function getMockLedgerEntries(): LedgerEntry[] {
  const baseEntries = [
    {
      id: '1',
      role: 'Senior Product Designer',
      company: 'TechCorp Inc.',
      status: 'Applied' as const,
      date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(), // 12 days ago
      lastActivity: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      truthScore: 85,
    },
    {
      id: '2',
      role: 'UX Lead',
      company: 'DesignStudio',
      status: 'Interview' as const,
      date: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(), // 17 days ago
      lastActivity: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
      truthScore: 72,
    },
    {
      id: '3',
      role: 'Product Manager',
      company: 'StartupXYZ',
      status: 'Ghosted' as const,
      date: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(), // 28 days ago
      lastActivity: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
      truthScore: 35,
    },
  ]
  
  return baseEntries.map((entry) => {
    const daysSince = Math.floor(
      (Date.now() - new Date(entry.date).getTime()) / (1000 * 60 * 60 * 24)
    )
    
    return {
      ...entry,
      echoNote: generateLedgerNote(entry, daysSince),
      priority: entry.status === 'Ghosted' || daysSince > 14 ? 'low' : 'high',
    }
  })
}

/**
 * Helper: Get time of day for context-aware dialogue
 */
function getTimeOfDay(): 'morning' | 'afternoon' | 'evening' {
  const hour = new Date().getHours()
  if (hour < 12) return 'morning'
  if (hour < 17) return 'afternoon'
  return 'evening'
}
